### ISSUE TITLE
Querying by $eq or $neq no longer working

### ISSUE THREAD

**Issue by mingard** [anywhichway/reasondb#15]
In version 2.5, the following query worked:
 ```Javascript
{$p: {name: {$neq: null}}}
```
I believe changes made in 2.6 (not released to npm) broken this functionality

**Comment by mingard** [comment]
@anywhichway Found the issue - 

https://github.com/anywhichway/reasondb/blob/master/lib/index.js#L439

Should be 
```javascript
set = objects ? new _set2.default() : {},
```
not 
```
set = objects ? new _set2.default() : {};
```

As there are preceding methods with comma delimination

**Comment by anywhichway** [comment]
@mingard Pushed v0.2.8 with a fix. Please verify if you would and then close. We will then push to npm.

**Comment by mingard** [comment]
@anywhichway verified fix

**Comment by anywhichway** [comment]
@mingard Thanks! npm package pushed.
