### ISSUE TITLE
Handle empty arrays

### ISSUE THREAD

**Issue by mingard** [anywhichway/reasondb#19]
If an object is inserted and the value of a key is `[]` the insert never completes. No errors are thrown either.

Example:
```js
{
  name: "John",
  friends: []
}
```

**Comment by anywhichway** [comment]
@mingard looking into this

**Comment by anywhichway** [comment]
@mingard I think we found the issue. May take a few days to address.

**Comment by mingard** [comment]
@anywhichway brilliant, thanks!

**Comment by anywhichway** [comment]
@mingard We are making progress on this. We have addressed un-resolving Promise. The code now continues, but we have a few failing unit tests. I expect it may take a couple more days. In the gnarly bowels of things.

**Comment by anywhichway** [comment]
@mingard All existing unit tests now passing! Adding some more unit tests to ensure this is properly addressed going forward. Should have you a branch for testing tomorrow.

**Comment by mingard** [comment]
@anywhichway that's fantastic. I'll test tomorrow and remove the hotfix in the wrapper. Thank you

**Comment by anywhichway** [comment]
@mingard there is a branch https://github.com/anywhichway/reasondb/tree/v0.2.10 you can pull to test the fix.

**Comment by mingard** [comment]
Thanks @anywhichway - will check this out shortly

**Comment by mingard** [comment]
@anywhichway works perfectly - I'm trying to make [reasondb-wrapper](https://github.com/mingard/reasondb-wrapper) node 5+ compatible, so generally have to test using `lib/index.js` rather than `src/index.js`. 

I hadn't realised the v0.2.10 tree only contained the updates in `src/index.js`

Anyway, thank you!

**Comment by anywhichway** [comment]
Great ... sorry, next time a branch is created will run browserify. Will promote branch in the next couple of days.
