### ISSUE TITLE
Firebase adapter?

### ISSUE THREAD

**Issue by tomByrer** [anywhichway/reasondb#20]
Is there a Firebase adapter?
This seems misleading: https://github.com/anywhichway/reasondb/blob/master/package.json#L22

**Comment by anywhichway** [comment]
We are working on a Firebase adapter. Got a little bit ahead of things by putting the keyword in the package.json file. Will keep this issue open and close it out when the adapter is done. Probably a couple of weeks out. Lots of other things cooking.

**Comment by joshua1** [comment]
Any progress or word on this @anywhichway ?

**Comment by anywhichway** [comment]
@joshua1 Sorry. Been very busy with other work. Not sure when we will get it done.

**Comment by anywhichway** [comment]
@joshua1 Sorry for long delay. Will not be adding a Firebase adapter. Will be focusing exclusively on adding adapters for databases that support key/value storage via puts and gets rather than the callback approach of Firebase. Will drop firebase reference from project.json file.
