### ISSUE TITLE
No way to search unordered array properties

### ISSUE THREAD

**Issue by codingmatty** [anywhichway/reasondb#25]
First, I like what this project has to offer, I hope you will continue working on it :)

I was playing around, creating my own store adapter for the Database that I want to use, and that seems to be good to go. But, I wanted to test some of the capabilities and ran into some issues with querying arrays. Basically, there is no real way that I could find to query objects based on the contents of an array property. See example below..

Example:
```javascript
class Person {
  constructor(name, friends) {
    this.name = name;
    this.friends = friends;
  }
}

const me = new Person('Matt', ['Jay', 'Logan', 'Sky']);

db.insert(me).exec().then(() => {
  db.select()
    .from({ $p: Person })
    // This doesn't work at all:
    .where({ $p: { friends: { $contains: 'Logan' } } })
    // This works, but I have to know the index :(
    .where({ $p: { friends: { 1: 'Logan' } } })
    // This doesn't work bc the `value` is not the actual array, it is a reference to the array..
    .where({ $p: { friends: { $: (value) => value.includes('Logan') } } })
    .exec()
    .then((cursor) => {
      cursor.forEach((row) => { console.log("Person", JSON.stringify(row[0])); });
    })
})
```

If you have a solution, that would be great, but otherwise I wanted to bring it to your attention, that this seems to be a real limitation.

**Comment by anywhichway** [comment]
@codingmatty Thanks for such a clear example. Will look into this over the next few days. If you are in the US, Happy 4th!

**Comment by anywhichway** [comment]
@codingmatty Fixed in latest release
