### ISSUE TITLE
Multiple instances communicating with one central server?

### ISSUE THREAD

**Issue by LoganDark** [anywhichway/reasondb#26]
Is this possible?

**Comment by anywhichway** [comment]
@LoganDark this is possible. I will try to post some guidance in the next few days.

**Comment by LoganDark** [comment]
Alright, thanks!

**Comment by anywhichway** [comment]
@LoganDark Sorry for the long delay. With the most recent release this is trivial. See the examples/redis directory. The magic come from ReasonDB providing its own server that will serve up a JavaScript file from /fos. This file has a remote ReasonDB proxy in it called ReasonDBServer. Just passing this proxy in as a start-up option to a local server joins the two servers. This can actually be daisy chained across servers.
