### ISSUE TITLE
Not a lot of updates recently...

### ISSUE THREAD

**Issue by tneward** [anywhichway/reasondb#29]
Is active development on this project still happening?

**Comment by anywhichway** [comment]
@tneward Our focus is currently on other things. The project that initially drove reasondb was suspended. And, although we continue to like the JOQULAR syntax, we found the underlying architecture we had implemented overly complex. Plus the size was getting too big for mobile. We are currently experimenting with another database anywhichway/anywhichway. We will push a README update later this week to make it clear. This being said, some pressure or support from other entities could change our direction!

**Comment by anywhichway** [comment]
@tneward We merged anywhichway/anywhichway into reasondb and addressed architectural issues. Still rough around the edges; but, a lot of enhancements. Closing this issue.
