### ISSUE TITLE
Client to Server Synchronization

### ISSUE THREAD

**Issue by anywhichway** [anywhichway/reasondb#4]
The addition of browser/server synchronization is under consideration. The feature would support automatic updating of objects on a server if updated by a client after retrieval from a server. The client would typically be a browser. The anticipated implementation would use sockets although a URL based http mechanism would be feasible.

This topic is open for questions, comments, and design thoughts. Give it a thumbs-up if it is important to you.

**Comment by nevf** [comment]
Progressive Web Apps and offline first are gaining momentum. There is real need for fully fledged database capabilities in the Browser that can be used offline, with sync + conflict resolution back to the server when a connection is available again. This could be days or weeks later.

By fully fledged I mean all CRUD operations, so from the user's perspective the app has all the same functionality whether they are online or offline. The Browser database world is unfortunately constrained to IndexedDB, so we need to build on top of that.

My own use case is to enable [Clibu](www.clibu.com) the Knowledge Base Web App I'm developing to work offline. Right now it uses MongoDB on the server along with realtime websocket push of updates to the Browser, but it has no offline capabilities. 

One option at this point is to use something like [Dexie.js](http://dexie.org/) along with it's [Syncable module](https://github.com/dfahlander/Dexie.js/wiki/Dexie.Syncable.js), but I can see that being a lot of work.  Another possibility is [PouchDB](https://github.com/pouchdb/pouchdb), however its append-only database model is of concern, especially in the Browser where resources are constrained.

Other libraries I've looked at include [rxdb](https://github.com/pubkey/rxdb) which uses PouchDB and [gun,js](http://gun.js.org/) but I don't consider it to be a real database and it is quite early days, however it does do real time sync.

I continue to be surprised that no one has yet come up with a modern NoSQL package that accomplishes what PouchDB and CouchDB do, clearly there is a now more of a need than ever.

**Comment by anywhichway** [comment]
Thanks for the input. Can't say I disagree. We will probably start with real-time sync of objects retrieved during current session and then progress to an offline first model. Both have been anticipated in the initial design. If you need something immediately, you might take a look at Meteor.
